version: '3'
services:
  sudoku-auth:
    image: sudoku/auth-boot:1.0.0
    container_name: sudoku-auth
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx100m -Xms100m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5002
    ports:
      - "8000:8000"
      - "5002:5002"
    external_links:
      - mysql:db
      - nacos:nacos
      - redis:redis
      - sentinel:sentinel
      - zipkin:zipkin
  sudoku-game:
    image: sudoku/game-boot:1.0.0
    container_name: sudoku-game
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx100m -Xms100m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5003
    ports:
      - "8300:8300"
      - "5003:5003"
    external_links:
      - mysql:db
      - nacos:nacos
      - redis:redis
      - sentinel:sentinel
      - zipkin:zipkin
  sudoku-gateway:
    image: sudoku/sudoku-gateway:1.0.0
    container_name: sudoku-gateway
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx100m -Xms100m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5004
    ports:
      - "9999:9999"
      - "5004:5004"
    external_links:
      - mysql:db
      - nacos:nacos
      - redis:redis
      - sentinel:sentinel
      - zipkin:zipkin
      - sudoku-auth:auth
  sudoku-monitor:
    image: sudoku/sudoku-monitor:1.0.0
    container_name: sudoku-monitor
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx100m -Xms100m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "7000:7000"
      - "5005:5005"
    external_links:
      - nacos:nacos
  sudoku-ums:
    image: sudoku/ums-boot:1.0.0
    container_name: sudoku-ums
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx100m -Xms100m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    ports:
      - "8100:8100"
      - "5006:5006"
    external_links:
      - mysql:db
      - nacos:nacos
      - redis:redis
      - sentinel:sentinel
      - zipkin:zipkin
