version: '3'
services:
  sudoku-auth:
    image: sudoku/auth-boot:1.0.0
    container_name: sudoku-auth
    ports:
      - 8000:8000
    external_links:
      - mysql:db
      - nacos:nacos
      - redis:redis
      - sentinel:sentinel
      - zipkin:zipkin
  sudoku-game:
    image: sudoku/game-boot:1.0.0
    container_name: sudoku-game
    ports:
      - 8300:8300
    external_links:
      - mysql:db
      - nacos:nacos
      - redis:redis
      - sentinel:sentinel
      - zipkin:zipkin
  sudoku-gateway:
    image: sudoku/sudoku-gateway:1.0.0
    container_name: sudoku-gateway
    ports:
      - 9999:9999
    external_links:
      - mysql:db
      - nacos:nacos
      - redis:redis
      - sentinel:sentinel
      - zipkin:zipkin
      - sudoku-auth:auth
  sudoku-monitor:
    image: sudoku/sudoku-monitor:1.0.0
    container_name: sudoku-monitor
    ports:
      - 7000:7000
    external_links:
      - nacos:nacos
  sudoku-ums:
    image: sudoku/ums-boot:1.0.0
    container_name: sudoku-ums
    ports:
      - 8100:8100
    external_links:
      - mysql:db
      - nacos:nacos
      - redis:redis
      - sentinel:sentinel
      - zipkin:zipkin
