version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.12.1
    container_name: kibana
    links:
      - elasticsearch:es
    depends_on:
      - elasticsearch
    environment:
      - "elasticsearch.hosts=http://es:9200"
      - TZ=Asia/Shanghai
    ports:
      - "5601:5601"
  # 需安装json_lines插件：docker exec -it logstash /bin/bash  cd /bin/ logstash-plugin install logstash-codec-json_lines
  logstash:
    image: logstash:7.12.1
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - TZ=Asia/Shanghai
    volumes:
      # 需要手动创建logstash.yml文件
      - /mydata/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /mydata/logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - "4560:4560"
      - "4561:4561"
      - "4562:4562"
      - "4563:4563"
